baseURL = "/"
languageCode = "en-us"
title = "Nick Arner"
# theme = "anubis"
theme = "ezhil"

copyright = "© Copyright Nicholas Arner, 2022"
RSSLink = ""
rssLimit = 20
logo = ""
orgName = ""
orgWebsite = ""
orgDescription = ""
staticDir = "static"
googleAnalytics = "UA-187116527-1"

#https://www.tomspencer.dev/blog/2018/08/03/deploying-a-hugo-powered-site-to-netlify-with-source-code-syntax-highlighting/
pygmentsCodeFences = true   # Enable triple backtick 'code fence' markdown
pygmentsUseClasses = false  # Add inline styles, no need to compile extra CSS

[author]
	name = "Nick Arner"
	email = "nicholasarner@gmail.com"

  # [params]
  # [menu]
  #     [[menu.main]]
  #     identifier = "main"
  #     name = "Main"
  #     url = "/home"
  #     weight = 10
  #
  #     [[menu.main]]
  #     identifier = "notes"
  #     name = "Notes"
  #     url = "/notes/"
  #     weight = 10


#http://cloudywithachanceofdevops.com/posts/2018/05/17/setting-up-google-analytics-on-hugo/
