baseURL = "/"
languageCode = "en-us"
title = "Nick Arner"
# theme = "anubis"
theme = "ezhil"

RSSLink = ""
logo = ""
orgName = ""
orgWebsite = ""
orgDescription = ""
staticDir = "static"
  


  # [params]
  # [menu]
  #     [[menu.main]]
  #     identifier = "main"
  #     name = "Main"
  #     url = "/home"
  #     weight = 10
  #
  #     [[menu.main]]
  #     identifier = "notes"
  #     name = "Notes"
  #     url = "/notes/"
  #     weight = 10
